DROP TABLE IF EXISTS VILLES ;
CREATE TABLE VILLES (CP INTEGER   ,
VILL VARCHAR(50),
PRIMARY KEY (CP) ) ;

DROP TABLE IF EXISTS CLIENT ;
CREATE TABLE CLIENT (NUMCLI VARCHAR(5)PRIMARY KEY,
NOMCLI VARCHAR(50),
PRNCLI VARCHAR(50),
ADRCLI VARCHAR(70),
CP INTEGER REFERENCES VILLES (CP)) ;

DROP TABLE IF EXISTS AGENCE ;
CREATE TABLE AGENCE (CODAGC VARCHAR(4) PRIMARY KEY   ,
NOMAGC VARCHAR(50),
CP INTEGER REFERENCES VILLES (CP)) ;

DROP TABLE IF EXISTS MATERIEL ;
CREATE TABLE MATERIEL (REFMAT VARCHAR(4)   ,
DESMAT VARCHAR(50),
PRILOC SMALLINT,
PRIMARY KEY (REFMAT) ) ;

DROP TABLE IF EXISTS CONTRAT ;
CREATE TABLE CONTRAT (NUMCONT BIGINT PRIMARY KEY  ,
DATCONT DATE,
DUREE SMALLINT,
NUMCLI VARCHAR(5) ,
CODAGC VARCHAR(4) ,
FOREIGN KEY (NUMCLI) REFERENCES CLIENT (NUMCLI),
FOREIGN KEY (CODAGC) REFERENCES AGENCE (CODAGC) ) ;

DROP TABLE IF EXISTS DETAIL_CONTRAT ;
CREATE TABLE DETAIL_CONTRAT (NUMCONT BIGINT   ,
REFMAT VARCHAR(4) ,
QTELOUE SMALLINT,
PRIMARY KEY (NUMCONT, REFMAT),
FOREIGN KEY (NUMCONT) REFERENCES CONTRAT (NUMCONT),
FOREIGN KEY (REFMAT) REFERENCES MATERIEL (REFMAT) ) ;

DROP TABLE IF EXISTS STOCK ;
CREATE TABLE STOCK (CODAGC VARCHAR(4) ,
REFMAT VARCHAR(4),
QTSTOCK INTEGER,
PRIMARY KEY (CODAGC ,REFMAT),
FOREIGN KEY (REFMAT) REFERENCES MATERIEL (REFMAT),
FOREIGN KEY (CODAGC) REFERENCES AGENCE (CODAGC) ) ;
